services:
  # Main COSMO application
  - type: web
    name: COSMORLT
    env: node
    buildCommand: npm install && cd form-docentes && npm install && npm run build && cd ../form-acudientes && npm install && npm run build && cd ../form-estudiantes && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgres://cosmo_rlt_user:cosmo_rlt_password@dpg-cp8f1e21hbls73fmk0tg-a.oregon-postgres.render.com/cosmo_rlt
      - key: DOCENTES_TOKEN
        value: cosmo-doc-o185zfu2c-5xotms
      - key: ACUDIENTES_TOKEN
        value: cosmo-acu-js4n5cy8ar-f0uax8
      - key: ESTUDIANTES_TOKEN
        value: cosmo-est-o7lmi20mfwb-o9f06j
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    routes:
      - type: rewrite
        source: /docentes/cosmo-doc-o185zfu2c-5xotms/*
        destination: /docentes/cosmo-doc-o185zfu2c-5xotms/index.html
      - type: rewrite
        source: /acudientes/cosmo-acu-js4n5cy8ar-f0uax8/*
        destination: /acudientes/cosmo-acu-js4n5cy8ar-f0uax8/index.html
      - type: rewrite
        source: /estudiantes/cosmo-est-o7lmi20mfwb-o9f06j/*
        destination: /estudiantes/cosmo-est-o7lmi20mfwb-o9f06j/index.html
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.json
        name: Content-Type
        value: application/json
      - path: /*.png
        name: Content-Type
        value: image/png
      - path: /*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /*.jpeg
        name: Content-Type
        value: image/jpeg
      - path: /*.svg
        name: Content-Type
        value: image/svg+xml
      - path: /*.woff
        name: Content-Type
        value: font/woff
      - path: /*.woff2
        name: Content-Type
        value: font/woff2
      - path: /*.ttf
        name: Content-Type
        value: font/ttf

  # PostgreSQL Database
  - type: pserv
    name: cosmo-postgres
    plan: free
    env: docker
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    autoDeploy: false

# Global environment variables
envVarGroups:
  - name: common-env
    envVars:
      - key: TZ
        value: America/Bogota 