services:
  # Main COSMO application
  - type: web
    name: COSMORLT
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DOCENTES_TOKEN
        value: cosmo-doc-o185zfu2c-5xotms
      - key: ACUDIENTES_TOKEN
        value: cosmo-acu-js4n5cy8ar-f0uax8
      - key: ESTUDIANTES_TOKEN
        value: cosmo-est-o7lmi20mfwb-o9f06j
    healthCheckPath: /test
    autoDeploy: true
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/*
      - type: rewrite
        source: /docentes/*
        destination: /docentes/*
      - type: rewrite
        source: /acudientes/*
        destination: /acudientes/*
      - type: rewrite
        source: /estudiantes/*
        destination: /estudiantes/*
      - type: rewrite
        source: /*
        destination: /index.html

  # PostgreSQL Database
  - type: pserv
    name: cosmo-postgres
    plan: free
    env: docker
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    autoDeploy: false

# Global environment variables
envVarGroups:
  - name: common-env
    envVars:
      - key: TZ
        value: America/Bogota 