services:
  - type: web
    name: pdf-filler-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    publishDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /js/*
        name: Cache-Control
        value: public, max-age=3600
      - path: /css/*
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /js/*
        destination: /js/$1
      - type: rewrite
        source: /css/*
        destination: /css/$1
      - type: rewrite
        source: /test
        destination: /test.html
      - type: rewrite
        source: /root-test
        destination: /root-test.html
      - type: rewrite
        source: /test.html
        destination: /test.html
      - type: rewrite
        source: /*
        destination: /index.html 