CREATE TABLE IF NOT EXISTS rectores_backup_2025_05_06 (
  id integer NOT NULL DEFAULT nextval('rectores_id_seq'::regclass),
  excel_id text,
  entiendo_la_informacion_y_acepto_el_trato_de_mis_datos_personal boolean,
  nombre_s_y_apellido_s_completo_s text,
  numero_de_cedula integer,
  genero text,
  lugar_de_nacimiento text,
  fecha_de_nacimiento date,
  lengua_materna text,
  numero_de_celular_personal text,
  correo_electronico_personal text,
  correo_electronico_institucional_el_que_usted_usa_en_su_rol_com text,
  prefiere_recibir_comunicaciones_en_el_correo text,
  tiene_alguna_enfermedad_de_base_por_la_que_pueda_requerir_atenc boolean,
  si_requiere_atencion_medica_urgente_durante_algun_encuentro_pre text,
  cual_es_su_numero_de_contacto text,
  tiene_alguna_discapacidad boolean,
  tipo_de_formacion text,
  titulo_de_pregrado text,
  titulo_de_especializacion text,
  titulo_de_maestria text,
  titulo_de_doctorado text,
  nombre_de_la_institucion_educativa_en_la_actualmente_desempena_ text,
  cargo_actual text,
  tipo_de_vinculacion_actual text,
  fecha_de_vinculacion_al_servicio_educativo_estatal date,
  fecha_de_nombramiento_estatal_en_el_cargo_actual date,
  fecha_de_nombramiento_del_cargo_actual_en_la_ie date,
  estatuto_al_que_pertenece text,
  grado_en_el_escalafon text,
  codigo_dane_de_la_ie_12_digitos bigint,
  entidad_territorial text,
  comuna_corregimiento_o_localidad text,
  zona_de_la_sede_principal_de_la_ie text,
  zona_de_la_sede_principal_de_la_ie2 text,
  direccion_de_la_sede_principal text,
  telefono_de_contacto_de_la_ie text,
  sitio_web text,
  correo_electronico_institucional text,
  numero_total_de_sedes_de_la_ie_incluida_la_sede_principal integer,
  numero_de_sedes_en_zona_rural integer,
  numero_de_sedes_en_zona_urbana integer,
  jornadas_de_la_ie_seleccion_multiple ARRAY,
  grupos_etnicos_en_la_ie_seleccion_multiple ARRAY,
  proyectos_transversales_de_la_ie text,
  estudiantes_o_familias_de_la_ie_en_condicion_de_desplazamiento boolean,
  niveles_educativos_que_ofrece_la_ie_seleccion_multiple ARRAY,
  tipo_de_bachillerato_que_ofrece_la_ie text,
  modelo_o_enfoque_pedagogico text,
  numero_de_docentes integer,
  numero_de_coordinadoras_es integer,
  numero_de_administrativos integer,
  numero_de_orientadoras_es integer,
  numero_de_estudiantes_en_preescolar integer,
  numero_de_estudiantes_en_basica_primaria integer,
  numero_de_estudiantes_en_basica_secundaria integer,
  numero_de_estudiantes_en_media integer,
  numero_de_estudiantes_en_ciclo_complementario integer,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

