services:
  - type: web
    name: form-docentes
    env: node
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 
      - key: DATABASE_URL
        fromDatabase:
          name: COSMO_RLT_db
          property: connectionString

databases:
  - name: COSMO_RLT_db
    databaseName: form_docentes
    user: form_docentes_user
    plan: free